coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  require_ci_to_pass: false
  notify:
    wait_for_ci: true
  github_checks:
    annotations: false
